version: '3.7'
services:
  web:
    container_name: ctr_getcoin
    build:
      context: .
    image: img_getcoin
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    command: './compose_cmd.bash'
